# Generated by Django 2.0.2 on 2018-03-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friends'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('user1', 'user2')},
        ),
    ]
