# Generated by Django 2.0.2 on 2018-03-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180317_2113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
