# Generated by Django 2.0.2 on 2018-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180317_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField()),
                ('receive_time', models.DateTimeField()),
                ('read_status', models.IntegerField()),
            ],
        ),
    ]
