# Generated by Django 2.0.2 on 2018-03-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receive_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(null=True),
        ),
    ]
