# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180319_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'other'), (3, 'Rather not say')], default=3),
        ),
    ]
