# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'other'), ('3', 'Rather not say')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
