# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180320_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
